const  menulist = [
    {
        title:'首页',
        key:'/admin/home',
        icon:'home'
    },
    {
        title:'商品',
        key:'/admin/products',
        icon:'shop',
        children:[
            {
                title:'种类管理',
                key:'/admin/category',
                icon:'shopping'
            },
            {
                title:'商品管理',
                key:'/admin/product',
                icon:'pay-circle'
            }
        ]
    },
    {
        title:'用户管理',
        key:'/admin/user',
        icon:'user'
    },
    {
        title:'权限管理',
        key:'/admin/roles',
        icon:'lock'
    },
    {
        title:'图形管理',
        key:'/admin/charts',
        icon:'bar-chart',
        children:[
            {
                title:'饼状图',
                key:'/admin/charts/pie',
                icon:'pie-chart'
            },
            {
                title:'折线图',
                key:'/admin/charts/line',
                icon:'line-chart'
            },
            {
                title:'柱状图',
                key:'/admin/charts/bar',
                icon:'bar-chart'
            }
        ]
    }
]

export default menulist